src/index.tsx, src/modules/Blocks/store/apis.ts, src/modules/Home/index.tsx, src/modules/NetworkRedirect/index.tsx, src/modules/Transactions/store/apis.ts
=> Add network redirect router

src/modules/Home/index.tsx
=> Calculate hash rate using average difficulty and time of the last 20 blocks

package.json, src/modules/Blocks/store/sagas.ts, src/modules/Search/store/sagas.ts, src/modules/Transactions/components/Detail/index.tsx, src/modules/Transactions/containers/index.tsx, src/modules/Transactions/store/sagas.ts, src/sagaMiddleware/index.ts, yarn.lock
=> Add try/catch to handle errors when getting transaction details' paramter

package-lock.json, package.json, public/locales/en/translation.json, public/locales/zh/translation.json, src/modules/MainnetCountdown/index.tsx
- support en/zh langauge
- past, present and future events' middle dots are in different colors
=> Add Starcoin key events timeline and adjust the layout

src/modules/Blocks/store/sagas.ts, src/modules/Transactions/store/sagas.ts, src/utils/constants.ts
1. update polling interval to 19 s
2. polling only in main page, block first page and transaction first page
=> optimize auto polling block and transactions

src/modules/Blocks/components/Detail/index.tsx
- Only show block's self events in the list
=> Fix block details' event list

src/utils/helper.ts
=> fix(getnetwork): networkInpath should match the proper networks

public/locales/en/translation.json, public/locales/zh/translation.json, src/common/Layout/Header/HeaderDownMD.tsx, src/common/Layout/Header/HeaderUpMD.tsx, src/common/Layout/index.tsx
=> Handle specific domain with warning on top

src/modules/Error404/address.tsx
=> Fix error 404 page text styles

.env, .vscode/settings.json, package.json, src/modules/AddressTransactions/components/List/index.tsx, src/modules/Transactions/components/Detail/index.tsx, yarn.lock
Reverts starcoinorg/starcoin-explorer#124
=> Revert "Wuliqiang"

.env, .vscode/settings.json, package.json, src/modules/AddressTransactions/components/List/index.tsx, src/modules/Transactions/components/Detail/index.tsx, yarn.lock
Reverts starcoinorg/starcoin-explorer#125
=> Revert "Revert "Wuliqiang""

src/utils/i18n.ts
fix bug  - language switching is not persistent   #121
=> fix bug  - language switching is not persistent

package.json, src/modules/AddressTransactions/components/List/index.tsx, src/modules/Transactions/components/Detail/index.tsx, yarn.lock
https://github.com/starcoinorg/starcoin-explorer/issues/119
=> download a user's transactions to csv

src/modules/Transactions/components/Detail/index.tsx
=> fix 查询任何不存在的交易都会被识别为地址

src/modules/Transactions/components/Detail/index.tsx
=> fix  148    infinite loop

src/modules/Address/components/TokenTable.tsx, src/modules/AddressTransactions/components/TransactionSummary/index.tsx, src/modules/Transactions/components/TransactionSummary/TransactionP2PItem.tsx, src/modules/Transactions/components/TransactionSummary/TransferTransactionSummary.tsx
=> address page transaction display    from to amount  if p2p

src/modules/Transactions/components/Detail/index.tsx
修复批量转账bug
https://github.com/starcoinorg/starcoin-explorer/issues/134
=> [fix] 交易详情批量转账的参数显示bug #134

src/modules/Address/components/TokenTable.tsx, src/utils/sdk.ts
=> token amount error and full name

src/modules/Transactions/components/TransactionSummary/TransactionP2PItem.tsx
https://github.com/starcoinorg/starcoin-explorer/issues/177
=> 修复 #177 关于地址的样式问题

src/modules/Address/index.tsx, src/modules/Blocks/components/Detail/index.tsx, src/modules/NetworkRedirect/index.tsx, src/modules/PendingTransactions/components/Detail/index.tsx, src/modules/Transactions/components/Detail/index.tsx, src/modules/Transactions/components/TransactionSummary/TransactionP2PItem.tsx, src/router/index.tsx
=> #158 包含tabs 页的 链接可以定位到tab内容

src/modules/Blocks/components/Detail/index.tsx, src/router/index.tsx
=> 区块信息详情TAB切换BUG修复

craco.config.js, package-lock.json, package.json, src/modules/Address/components/CodeContent.tsx, src/utils/sdk.ts
=> add disassemble feature
